image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  script:
    - echo "Deploying to Github Pages"
    - git init
    - git remote add origin <git@github.com:painiago/arquiproject.git>
    - git add .
    - git commit -m "Deploy"
    - git push -f origin main
